# References:
# http://genbattle.bitbucket.org/blog/2016/01/17/c++-travis-ci/
# https://github.com/genbattle/dkm/blob/9c893efb556516f4b121a6201b66e000f838dd59/.travis.yml
#
# Use new trusty images, should yield newer compilers and packages
sudo: required
dist: precise
language: cpp

# https://docs.travis-ci.com/user/installing-dependencies
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libssl-dev cmake g++-multilib

script:
  - ./build.sh x64
